version: 2

sources:
  - name: staging
    database: zoomcamp-422109
    schema:
      trips_data_all

      # loaded_at_field: record_loaded_at
    tables:
      - name: green_trips_all
      - name: yellow_trips_all

